### ISSUE TITLE
Dropdown menu not visible in webkit (Safari)

### ISSUE THREAD

**Issue by adamkolson** [Postleaf/postleaf#10]
### Summary

Menu on the dropdown menu with the Postleaf cut off in Safari

### Steps to Reproduce

1. Open Safari
2. Click the Postleaf icon in the admin panel

### Additional info

- Postleaf version: 6a0bee9  
- Node version:
- Affected browsers: Safari
- Operating system: macOS
![screen shot 2017-04-20 at 4 58 57 pm](https://cloud.githubusercontent.com/assets/644000/25252521/53e3563c-25eb-11e7-9596-d3c686cb2d73.png)

---

Note: This issue tracker is ONLY for bug reports and feature requests. If this is a personal support issue, please ask on the forum instead: community.postleaf.org

**Comment by adamkolson** [comment]
Just as sometimes things are related, using Coda (webkit) the web inspector is covered by the blog content on the default theme. If that helps with the `z-index` juggling. Obviously not a big deal as I can just use Atom and Chrome for development.
![screen shot 2017-04-20 at 6 00 49 pm](https://cloud.githubusercontent.com/assets/644000/25254439/8d1d81a4-25f3-11e7-9031-3b5df442d906.png)

**Comment by claviska** [comment]
Simple fix. Safari doesn't seem to honor overflow-x when overflow-y is set. I like the solution in 43254fa better anyway since it keep the logo visible if the admin menu has to scroll.

**Comment by claviska** [comment]
That other glitch looks like a problem with the web view of whatever app you're using. It doesn't seem to happen in Safari itself.
