### ISSUE TITLE
maxWidth for dynamic images // feature request

### ISSUE THREAD

**Issue by M8inC** [Postleaf/postleaf#102]
Dynamic Images is a great feature! 
But i would like to define a maximum image width, because my (your ;) ) theme/template has a maximum content-image-width of 875px. So it is not required to load an image wider than that size.

I solved it for myself by changing line 87 in file /source/modules/dynamic_images.js 
from 
`for(let width = 200; width < upload.width; width += 200) {` 
to 
`for(let width = 200; width < 801; width += 200) {`

but it would be cool if this could be done from the admin settings or in theme.json. As far as i can see does this change has no impact on other functions.

Best Regards,
Martin

**Comment by claviska** [comment]
Added in #106. I'd love a PR that documents how to set this in `.env` 👍
