### ISSUE TITLE
NGINX Support

### ISSUE THREAD

**Issue by claviska** [Postleaf/postleaf#11]
This is already a common request, so let's work on getting Nginx supported officially through the installer.

**Comment by webanvesh** [comment]
Very Interesting Feature / upgrade.

**Comment by trentyarwood** [comment]
I have managed to get it working using nginx:

Thanks to Cory for [this SO link](https://stackoverflow.com/questions/12924896/rewrite-all-requests-to-index-php-with-nginx/12931128#12931128) which helped me get it working: 

Config file (note that I'm completely terrible at this, so the file might be a bombsite; tips for improvement appreciated).


```
server {
        listen 80;
        server_name myserver
        return 301 https://$host$request_uri;
       #defaults to https because what is wrong with you?
}

server {
        listen 443 ssl;
        server_name myserver;
#ssl
     ssl_certificate      /home/user/.ssh/server.crt;
     ssl_certificate_key  /home/user/.ssh/server.key;
     ssl_session_timeout  5m;
     ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
     ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-S$
     ssl_prefer_server_ciphers   on;
     ssl_dhparam /etc/nginx/conf.d/dhparams.pem;
     add_header Strict-Transport-Security max-age=31536000;        

#proxy config
     client_max_body_size 10m;
     client_body_buffer_size 128k;
     proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
     proxy_set_header Host $http_host;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header X-Forwarded-Proto https;
     proxy_redirect     off;
     proxy_http_version 1.1;
     proxy_set_header Connection "";
     proxy_cache_bypass $cookie_session;
     proxy_no_cache $cookie_session;
     proxy_buffers 32 4k;
     send_timeout 5m;
     proxy_read_timeout 240;
     proxy_send_timeout 240;
     proxy_connect_timeout 240;
#end ssl/proxy stuff

        access_log /var/log/nginx/postleaf.access.log;
        error_log /var/log/nginx/postleaf.error.log;

        root /var/www/postleaf/;

  location ~ \.php$ {
        fastcgi_pass        127.0.0.1:8005;
        include             fastcgi_params;
        fastcgi_param       PATH_INFO $fastcgi_script_name;
        fastcgi_param       SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors on;
        fastcgi_buffers 8 16k;
        fastcgi_buffer_size 32k;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
        try_files = $uri @missing;
        fastcgi_index index.php;
        }

  location / {
        index index.php index.html index.htm;
        try_files $uri $uri/ /index.php$args;
        }

  location ~ /\.ht {
        deny all;
        }

  location @missing {
        rewrite ^ $scheme://$host/index.php permanent;
        }
}

```

**Comment by NinoSkopac** [comment]
@trentyarwood You have way too much code in your snippet. You should only focus on the essentials, and let others build on top of it, with, for example, SSL support.

@claviska Is this the only code that needs to be translated to nginx syntax?

```
# Rewrites
RewriteEngine On

# Forbid access to these folders
RewriteRule ^backups/ - [F]

# Route requests through index
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]
```

**Comment by claviska** [comment]
Yep, Postleaf uses Slim so everything that doesn't exist needs to be routed through `index.php`. We can probably use [this config](http://docs.slimframework.com/routing/rewrite/#nginx) as a baseline to support Nginx.

**Comment by jclacherty** [comment]
I have it working with the following config.

```
server {
        listen  80;
        server_name postleaf.mydomain.com;

        access_log /var/log/nginx/postleaf.access.log;
        error_log /var/log/nginx/postleaf.error.log error;

	return 301 https://$host$request_uri;
}

server {
	listen	443;
	ssl on;
	server_name postleaf.mydomain.com;

	access_log /var/log/nginx/postleaf.access.log;
	error_log /var/log/nginx/postleaf.error.log error;

	root /opt/postleaf/;
	client_max_body_size 100M;
	fastcgi_buffers 64 4K;

	gzip off;

	index index.php;

	try_files $uri /index.php;

	location = /robots.txt {
		allow all;
		log_not_found off;
		access_log off;
	}

	location ~ ^/(?:\.htaccess|data|config|db_structure\.xml|README){
		deny all;
	}

	location ~ ^/backups/ {
		return 403;
	}
 
	location /index.php {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
		fastcgi_param HTTPS on;
		fastcgi_pass php-handler;
	}
}
```

**Comment by jclacherty** [comment]
I lie. It almost works. When you click on a post it goes to Postleaf's 404. Which seems to suggest it's a Postleaf issue rather than nginx.

```
192.168.0.1 - - [01/Aug/2016:15:15:34 +1000] "GET /welcome-to-postleaf HTTP/1.1" 404 4159 "https://postleaf.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0"
```
So judging by the access log, nginx has correctly redirected to index.php and Postleaf is returning the 404.

**Comment by claviska** [comment]
That path is routed through Slim, so it's more likely that this is an Nginx config issue than a Postleaf issue. I'll work on Nginx support soon. Still open to sample configs if someone has a working one.

**Comment by jclacherty** [comment]
Ok, it just works now. Wonder if it's some sort of weird date/time thing... After installing I changed the timezone to Australia.

**Comment by claviska** [comment]
I'm not an Nginx guru, so correct me if I'm wrong, but due to the way the config seems to work, I don't think this is something we'll be able to do through the installer. It's going to require some preconfig. We may just need to document a general config and have the user update it manually before installing.

The _good_ news is you only have to configure a couple things:

- All requests made to a file or directory that _doesn't_ exist need to go to `index.php`
- Everything inside the backups folder should be restricted

The bad news is we can't reliably detect the server software that's running, so this will have to be an option in the installer. 🤔

**Comment by joshas** [comment]
> due to the way the config seems to work, I don't think this is something we'll be able to do through the installer

You are correct, NGINX configuration files are stored separately, way out of web apps reach.

**Comment by calmdev** [comment]
I setup nginx and a `postleaf.dev` site to try running it locally on OSX using port 6500 (have other stuff bound to 80). This is what's working for me:

```shell
server {
  listen                *:6500;
  server_name           postleaf.dev;
  access_log           /path/to/postleaf.dev.access.log;
  error_log            /path/to/postleaf.dev.error.log;

  location / {
    root  /path/to/postleaf/app;
    try_files  $uri  $uri/  /index.php?$args;
    index index.php;
  }

  location ~ \.php$ {
    root  /path/to/postleaf/app;
    try_files  $uri  $uri/  /index.php?$args;
    index  index.html index.htm index.php;

    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_intercept_errors on;
    include fastcgi_params;
  }

}
```

![screen shot 2016-08-04 at 10 05 22 am](https://cloud.githubusercontent.com/assets/461249/17404870/64612804-5a2b-11e6-857c-c9440cf1eafc.png)
![screen shot 2016-08-04 at 10 05 35 am](https://cloud.githubusercontent.com/assets/461249/17404871/646bfdb0-5a2b-11e6-9fa5-c2d6d9753a01.png)
![screen shot 2016-08-04 at 10 05 52 am](https://cloud.githubusercontent.com/assets/461249/17404874/64885fd2-5a2b-11e6-96c6-845851881311.png)
![screen shot 2016-08-04 at 10 06 15 am](https://cloud.githubusercontent.com/assets/461249/17404872/647d183e-5a2b-11e6-9de2-a411d8453d89.png)
![screen shot 2016-08-04 at 10 07 32 am](https://cloud.githubusercontent.com/assets/461249/17404873/64857042-5a2b-11e6-86eb-d257ee95d554.png)

**Comment by doughnet** [comment]
If someone could also help out with a Caddy rewrite code would be awesome.  I tried to see if I could figure it out myself but unfortunately wasn't able to.

Reference:  https://caddyserver.com/docs/rewrite

**Comment by claviska** [comment]
Looks like we have a good sample config. Closing since there's nothing we can preconfigure with the installer.

Tutorial here: https://www.postleaf.org/running-postleaf-on-nginx

Thanks @calmdev!
