### ISSUE TITLE
Wrong revisions

### ISSUE THREAD

**Issue by karsasmus** [Postleaf/postleaf#14]
### Summary

I created a post with slug `untitled post`. After post was created, I opened it again, changed content and saved again.

I created a new post again. I opened `post settings`, clicked `revisions tab` and saw the revisions from the previous `untitled post`. I was able to open the first post's preview.
 
I closed Chrome, stopped and restarted Postleaf and deleted all Postleaf cookies, but revisions are shown.

### Additional info

- Postleaf version: master
- Node version: 6.10.2
- Affected browsers: Chrome 58
- Operating system: Ubuntu

---

Note: This issue tracker is ONLY for bug reports and feature requests. If this is a personal support issue, please ask on the forum instead: community.postleaf.org

**Comment by claviska** [comment]
Looks like what's happening is, if you create a new post, all revisions are loaded. Existing posts seem to be loading only the correct revisions. Fix on the way.
