### ISSUE TITLE
[proposal] Add postinstall to package.json

### ISSUE THREAD

**Issue by karsasmus** [Postleaf/postleaf#15]
### Summary
Add 
```javascript
"scripts": {
    "postinstall": "gulp build"
},
```
to `package.json` to run `gulp build` after install

---

Note: This issue tracker is ONLY for bug reports and feature requests. If this is a personal support issue, please ask on the forum instead: community.postleaf.org

**Comment by claviska** [comment]
Good idea. Saves a step.
