### ISSUE TITLE
Timezone issues during installation

### ISSUE THREAD

**Issue by joshas** [Postleaf/postleaf#18]
Default timezone is 'America/New_York'. If server has different timezone set, initial posts might not be displayed until user changes timezone in Postleaf advanced settings or some time passes until pub_date will be valid for that timezone. This might bring some confusion for some users.
Maybe it would be nice to put timezone selection on setup screen, or even try to get timezone automatically from PHP settings during setup?

**Comment by claviska** [comment]
Good point, it belongs in the installer along with language. This won't make the patch release but I'll work on it soon.

**Comment by claviska** [comment]
To avoid overcomplicating the installer, I've changed the default posts dates to Postleaf's launch date in 9592f64. This will prevent the issue you mentioned.

In the future, I'd like to make a more elaborate installer. Maybe a multipage ("wizard") version that takes you through each step. Until then, timezone and language will remain in settings :)

**Comment by joshas** [comment]
> In the future, I'd like to make a more elaborate installer.
I like one step installer, you should keep it simple as it is. Maybe setting other options to sensible defaults will be enough to keep them out of installer?

**Comment by claviska** [comment]
I like the one-step installer too, but Pagekit has a [pretty sweet concept](https://www.youtube.com/watch?v=JIbxduPy9Qs&t=130) that's very easy to use. If anything else gets added to Postleaf's installer, it will probably have to go that route.
