### ISSUE TITLE
Image Path Breaks (when using uploader)

### ISSUE THREAD

**Issue by andrewbiddinger** [Postleaf/postleaf#19]
### Issue Summary

I set up Postleaf within a folder on my site (/postleaf-beta/). When uploading an image, the image displays in preview (at first) but then breaks when viewing the post. The image path seems to have extra folders added to the path that do not exist ("postleaf-beta/postleaf-beta/postleaf-beta/[the image]"), which is why the image shows as broken. 

 
### Steps to Reproduce

Tell us how to replicate the problem.

1. Setup Postleaf site in a /directory/directory
2. Upload an image
3. The image is broken

### Additional info

- Postleaf version: 1.0.0-beta2
- PHP version: 5.6.19
- Affected browsers: all
- Operating system: MAC OS

**Comment by claviska** [comment]
Thanks for reporting this. The issue was a missing `/` at the end of the base URL which caused TinyMCE to generate the wrong path.

**Comment by claviska** [comment]
You can grab the latest release `1.0.0-beta3` to get this fix. To update, swap out `index.php` and the `source` folder.

**Comment by andrewbiddinger** [comment]
Thank you, works great!
