### ISSUE TITLE
Error: Template missing: blog.hbs

### ISSUE THREAD

**Issue by vanloc0301** [Postleaf/postleaf#24]
After installing the Postleaf, I have error when to go to `localhost/postleaf/app`:

```
Application Error
Template missing: blog.hbs

localhost
```

And have problem like this:

![animation](https://cloud.githubusercontent.com/assets/4168981/17275035/1dab899a-5724-11e6-85ba-c953015e28d5.gif)

You can see when press button install, the bar process appear quick. And it not auto redirected to homepage after install success. I think you need navigation to homepage after install success.

**Comment by claviska** [comment]
Sorry, you'll need to download the default theme from github.com/postleaf/range and place it into `content/themes/range`. This is missing from the current build process but will be added soon. Then simply refresh and you should be good to go.

**Comment by vanloc0301** [comment]
Thanks, @claviska . Seem when to installing success, it does not save username and password to the database. I check in phpmyAdmin at table `postleaf_users` not have any rows contains in this. I log in at fields `Pick a Username` and `Create a Password`.

**Comment by claviska** [comment]
Strange, what does your error log show from when you installed it? Did the default settings and posts get inserted?

**Comment by vanloc0301** [comment]
The Postleaf is connected successfully with the database because it auto a generates 7 table. You can see at here:

![capture](https://cloud.githubusercontent.com/assets/4168981/17277713/bd45d330-5773-11e6-8cb7-14c517c50b86.PNG)
 
At table `postleaf_users` not have any rows.

**Comment by claviska** [comment]
I understand that, but need to see your PHP error log to identify what went wrong.

**Comment by vanloc0301** [comment]
I found this log.

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Invalid slug: admin' in C:\wamp64\www\postleaf\app\source\classes\User.php:41
Stack trace:
#0 C:\wamp64\www\postleaf\app\source\installer\install.php(213): Postleaf\User::add('admin', Array)
#1 {main}
  thrown in C:\wamp64\www\postleaf\app\source\classes\User.php on line 41
```

**Comment by claviska** [comment]
Perfect. I need to add a try/catch to this as certain slugs are restricted. For now, use something other than "admin". Delete database.php and retry the install :)

Thanks!

**Comment by vanloc0301** [comment]
It's working. Thank you very much.

You should update exception in README.md is not set Username is: `admin` or `administrator`(I think like this).

**Comment by claviska** [comment]
I've added a check for this so you'll see an error message if you use a reserved username. Thanks for reporting this!
