### ISSUE TITLE
Use bluebird promises to improve performance

### ISSUE THREAD

**Issue by idietmoran** [Postleaf/postleaf#25]
Built in node.js Promises are 4x slower than blue bird, It's better to bring in the package bluebird and add the line ```js const Promise = require('bluebird'); ```

I can do a PR if you think it's warranted, but it's probably a good idea overall to do it.

**Comment by claviska** [comment]
I was wondering about Bluebird, but wasn't aware it was actually faster. Good to know. It's already being used by some of Postleaf's deps, so I'm don't mind adding it to `package.json`. A PR would be great.

We could probably use [`Promise.mapSeries`](http://bluebirdjs.com/docs/api/promise.mapseries.html) to address #5 as well.
