### ISSUE TITLE
Enviroments without MySQL password can't install postleaf

### ISSUE THREAD

**Issue by Zeokat** [Postleaf/postleaf#26]
### Issue Summary

MySQL password is not always required to access to database And it even needs to be 8 chars length.
MySQL servers not always are password protected, into developing enviroments MySQL don't have a default password also (XAMPP, etc...).
In short, don't allow users install PostLeaf if their database dont have a password is kinda weird (this dont happens in most of CMS, Wordpress for example).
The restriction of request an 8 chars length MySQL password has also nosense, since this password is not setup by postleaf is a server side decision.

### Steps to Reproduce

Simply install and leave the database password field empty.

### Additional info

- Postleaf version: 1.0.0 beta3
- PHP version: 7
- Affected browsers: All tested (Chrome, FireFox, Opera, etc)
- Operating system: Tested on Windows and Linux (Windows running XAMPP and Linux running Apache+MariaDB+PHP7).

**Comment by claviska** [comment]
The eight character requirement is for the user's password, not the database password.

Although I strongly disagree with using a blank database password even in a dev environment, I understand that in some instances it may be appropriate or even beyond the developer's control, so I'll remove the check for the database password.

You can wait for the next patch version `1.0.0-beta4` or simply remove `db-password` from the array in `install.php` and run the installer again.
