### ISSUE TITLE
PHP was better than NodeJS

### ISSUE THREAD

**Issue by doughnet** [Postleaf/postleaf#28]
Can't even get this to install on a fresh Debian 8 installation.

root@postleaf:/var/www/postleaf# node app.js
Error: Postleaf failed to start! ð
SequelizeUniqueConstraintError: Validation error

Maybe work on better installation guides?  The PHP version of PostLeaf was easy to install ... so far pretty disappointed in how the NodeJS version is thus far.

**Comment by juan-manuel-alberro** [comment]
Try running `gulp build` twice, that fixed the problem un my local environment. If that didn't worked download the latest version from alpha.

**Comment by doughnet** [comment]
running it twice did work ... guess thats good; but still way worse and less of a chance i will ever use postleaf in production with the complexity/inconvenience of NodeJS/NPM.

**Comment by claviska** [comment]
The alpha is intended for developers to work out bugs and improve the build/dist process. By their nature, Node apps are more difficult to install than PHP apps.

We're all learning here, so let's keep a positive tone and work through these early issues. 🙂

Although dev will probably remain the same, I haven't determined what the officially supported process for production will look like. One approach we're experimenting with is with Docker. It's still early, but I encourage anyone with container experience to help us improve it:

https://github.com/lukewatts/postleaf-docker

I'm not saying definitively that we're going to use Docker, but it looks like a promising approach that reduces these types of issues. I'm very much open to suggestions.

Ultimately, the goal is to find a solution that makes it easy and reliable to install Postleaf on a variety of platforms so anyone who wants to DIY can do so.

**Comment by lukewatts** [comment]
I've also just finsihed an Ansible playbook which is very straightforward to install and run on Debian/Ubuntu. No prior Ansible knowledge required.

[https://github.com/lukewatts/postleaf-playbook](https://github.com/lukewatts/postleaf-playbook)

**Comment by doughnet** [comment]
Nice. But by doing a product in docker or ansible will eliminate anyone using shared hosting. I feel that is a bad idea; because users that want something "easy" are also the ones that use shared hosting environments.

**Comment by lukewatts** [comment]
@doughnet I don't know of any shared hosts that run NodeJS apps.

I don't think every CMS needs to cater to the lowest common denominator. Nor should they. There are plenty of CMS options already out there that run on shared hosting.

Anyways, this isn't a forum so I'm going to leave it there. Basically if you want to give Postleaf another go you can try the Docker container or the Ansible playbook. If you have issues or questions about those please let me know.
