### ISSUE TITLE
hhvm support

### ISSUE THREAD

**Issue by jclacherty** [Postleaf/postleaf#29]
Great job Cory! I have Postleaf working with nginx and php5-fpm but it doesn't seem to work with my preferred PHP server hhvm. Would be good to get this going.

**Comment by claviska** [comment]
I don't have any experience with `HHVM`, but if you have a basic NGINX config please [share it here](https://github.com/Postleaf/postleaf/issues/11).

If you're interested in running Postleaf on additional servers, please add a feature request to [community.postleaf.org](https://community.postleaf.org) so we can open it up for discussion (trying to keep GitHub issues just for 🐞  and features I've committed to adding). If there's enough interest, I'll definitely look at getting it supported :)

Thanks!

**Comment by jclacherty** [comment]
Already shared nginx config in that issue.
