### ISSUE TITLE
Postleaf installer

### ISSUE THREAD

**Issue by lukewatts** [Postleaf/postleaf#29]
A global npm package which could be used to install new Postleaf projects.

So running `npm install -g postleaf-install` to install the package globally

Then you could run `postleaf-install new some-project` or `postleaf-install new /path/to/install/in`.

Running this would create a fully functioning Postleaf project without the needs for `npm install` or `gulp build`.

**Comment by claviska** [comment]
I think #27 is the best approach for this (at least for now). I don't want to get too sidetracked during this phase. There is currently an npm repo, but the preferred method is git/npm.

With the latest alpha, you don't need to run the build process (unless you want to do front end dev), so a lot of the installation pains should be gone now :)
