### ISSUE TITLE
Scrollbar issues in Advance tab

### ISSUE THREAD

**Issue by vanloc0301** [Postleaf/postleaf#30]
### Issue Summary

Seem have two scrollbar auto-appear when I scroll mouse up and down.
It seems problem at CSS.

### Steps to Reproduce

Tell us how to replicate the problem.

![animation](https://cloud.githubusercontent.com/assets/4168981/17283892/c8324bcc-57df-11e6-8e00-8e163b57f056.gif)

### Additional info

- Postleaf version: 1.0.0-beta3
- PHP version: 5.6.19
- Affected browsers: Chrome
- Operating system: Windows 7 x64.

**Comment by claviska** [comment]
Postleaf uses a JS helper to stretch the body down. Try clearing cache and refreshing and make sure there aren't any JS errors in your console.

I can't replicate this in the latest Chrome on Mac or Windows.

Let me know what you find.

**Comment by vanloc0301** [comment]
Yeah, I'm clear cache and don't found any JS error in console when scroll mouse to up and down(continuity about 3-4 scroll this bug will appear).

I am using Chrome 52 stable and 54 dev.

Only fail with Chrome, tested in Firefox and IE it working correctly.

Seem this error not clear and don't have anyone have this mistake. You also tested, I think a problem with me.

So, I will close this issues. Thank you very much @claviska
