### ISSUE TITLE
SequelizeUniqueConstraintError: Validation error

### ISSUE THREAD

**Issue by abecks** [Postleaf/postleaf#33]
### Summary

Running `node app.js` returns:

``SequelizeUniqueConstraintError: Validation error``

### Steps to Reproduce
1. Start up a CentOS 7.3 server
2. Install Postleaf dependencies
3. Run `gulp build`
4. Run `node app.js`

### Additional info

Using CentOS 7.3, Node 7, sqlite 3, GraphicsMagick 1.3.25, after running `gulp build`

**Comment by abecks** [comment]
Looks like running `node app.js` twice works the second time.

**Comment by venatoria** [comment]
Refer to #22 solved there

**Comment by claviska** [comment]
Resolved with 48eb7c4.
