### ISSUE TITLE
Database error during installation

### ISSUE THREAD

**Issue by joshas** [Postleaf/postleaf#36]
### Issue Summary

Trying to install latest version built from git. After filling in all required fields I get following error message:
> Unable to create the owner user: Database error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'twitter' in 'field list'

### Additional info

- Postleaf version: 1.0.0-beta5
- PHP version: 5.6.18

Column `twitter` is missing in app/source/defaults/default.database.sql .

**Comment by claviska** [comment]
Fixed in 1.0.0-beta6, which I'll push out in a minute since it breaks the installer. Thanks for reporting this.

**Comment by claviska** [comment]
Available now as a dist: https://www.postleaf.org/download
