### ISSUE TITLE
Broken links in Available Backups table

### ISSUE THREAD

**Issue by mwender** [Postleaf/postleaf#37]
I've tested the Download and Delete buttons in the Available Backups table, and I've found they are broken (*note: I haven't tested the Restore button*):

![Broken links in Available Backups table](https://dl.dropboxusercontent.com/s/03hcxi4fcpa7l3u/2016-08-03%20at%202.45%20PM.jpg)

Updating the path for the download handler in `app/source/scripts/settings.js` fixes the Download button:

```
    // Download backup
    $('.available-backups').on('click', '[data-download-backup]', function() {
        location.href = Postleaf.url(
            'backups/' + encodeURIComponent($(this).attr('data-download-backup'))
        );
    });
```

**Comment by claviska** [comment]
They're working for me. The code sample provided removes the `api/` path which would cause it to break (see the grouped routes in [`index.php`](https://github.com/Postleaf/postleaf/blob/master/app/index.php#L57-L103)).

Are you running Postleaf from a subfolder? Which beta is it?

**Comment by mwender** [comment]
I'm running Postleaf in my vhost's webroot. I just updated to Beta-5 today, but I noticed the issue before that. I believe I was at Beta-4.

![Download backup links not working](http://g.recordit.co/DIw3Jsyl9V.gif)

**Comment by claviska** [comment]
This is most likely an Nginx config issue. We don't have an official Nginx config yet, but follow and help us out with #11 if you can.

**Comment by mwender** [comment]
@claviska - that makes sense. I'm glad I included the gif which included the NGINX clue.

**Comment by calmdev** [comment]
screenshots of this working on nginix can be found here https://github.com/Postleaf/postleaf/issues/11#issuecomment-237565037

**Comment by claviska** [comment]
Closing because I'm 99.9% sure this is a server config issue. Check @calmdev's example and see if that helps.
