### ISSUE TITLE
Broken URLs on 1.0.0-alpha.3

### ISSUE THREAD

**Issue by lukewatts** [Postleaf/postleaf#41]
### Summary

I've followed the instructions for [Installing Postleaf on Digital Ocean](https://www.postleaf.org/installing-postleaf-on-digitalocean) using the tagged version `1.0.0-alpha.2` but when I run `node app.js` I get the following url `http://34.253.2.242/undefined/install`

See the screenshot below:

![liiw7j](https://cloud.githubusercontent.com/assets/4622166/25602685/c1af01a6-2eed-11e7-89a2-20245659db1e.jpg)

### Steps to Reproduce

Follow the tutorial with `1.0.0-alpha.2`

### Additional info

- Postleaf version: 1.0.0-alpha.2
- Node version: 7.9.0
- Affected browsers: N/A
- Operating system: Ubuntu 16.04

**Comment by claviska** [comment]
I did this install multiple times yesterday and didn't run into that. Can you verify the APP_URL in `.env` and try to dig into the source of that? Can't seem to replicate it.

**Comment by lukewatts** [comment]
I've started from scratch on a new AWS EC2 Ubuntu 16.04 instance.

Heres the start of my `.env` file:
 ```
# App
NODE_ENV=development
APP_URL=http://34.248.212.46:3000/
APP_PORT=3000
```
Still having the same issue.

**Comment by claviska** [comment]
Remove the :3000 from APP_URL. Make sure you've setup nginx too.

**Comment by lukewatts** [comment]
The :3000 was the problem. Getting mixed up between the last one and this one. Ended up with a hybrid .env file. But I'm very close now to have an Ansible Playbook done now also.
