### ISSUE TITLE
Template missing

### ISSUE THREAD

**Issue by cosmospham** [Postleaf/postleaf#42]
### Issue Summary

After install Postleaf. I can use admin panel. But it said that:

```
Application Error
Template missing: blog.hbs

postleaf.test
```

I check and there is no `range` themes folder; nothing in `/app/content/themes` folder.

### Steps to Reproduce

Install app as the README.

### Additional info

I use Postleaf both HEAD ver and 1.0.0-beta6/ commit 4c4a656 

```
node -v
v6.3.1

npm -v
3.10.3

php --version
PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 08:17:07)

lsb_release -d
Description:	Debian GNU/Linux 8.5 (jessie)
```

**Comment by claviska** [comment]
You have to install the [range theme](https://github.com/Postleaf/range) when you build. This is included in the dist, and will be included as part of the build process after beta.

**Comment by cosmospham** [comment]
Done. Thank you.

**Comment by claviska** [comment]
I added a note about this to the readme to make this more clear.
