### ISSUE TITLE
Password reset does not work

### ISSUE THREAD

**Issue by jclacherty** [Postleaf/postleaf#43]
### Issue Summary

The password reset does not work.

### Steps to Reproduce

1. Go to admin login page and click on the forgot password link
2. Enter your username
3. Click on link in the password reset email
4. Put new password in both fields and click submit.

### Expected Response
Success or go to admin dashboard.

### Actual Response
"Invalid Username" shown on screen.

### Additional info

The rendered password reset page does not have values for the two hidden fields `username` and `token`, as such the POST on clicking submit does not have the `username` or `token` in its POST parameters.

It appears as though the following lines in login.reset.hbs are not being rendered correctly.

```
        <input type="hidden" name="username" value="{{@request.get.username}}">
        <input type="hidden" name="token" value="{{@request.get.token}}">
```

**Comment by claviska** [comment]
Works for me. The email you receive will have a link that should look something like this:

```
http://your-domain.com/admin/login/reset/?username=your-username&token=abcd1234
```

Clicking the link should take you to that page, so make sure `username` and `token` are still in the query string.

From the reset page, view the rendered HTML source to check for the these values:

```html
<input type="hidden" name="username" value="your-username">
<input type="hidden" name="token" value="abcd1234">
```

As long as those are set, everything should be working properly. Can you follow those steps and let me know if any of them are failing for you?

Also, are you on Apache, Nginx, or another server?

**Comment by claviska** [comment]
Any update on getting this to work? Are you using Apache or another web server?

**Comment by jclacherty** [comment]
Running nginx. The link I'm sent is correct:
```
https://mydomain.com/admin/login/reset?username=myuser&token=mytoken
```
Clicking the link takes me to Safari and the hidden fields are not populated with values:
```html
    <div class="form-group">
        <input type="hidden" name="username" value="">
        <input type="hidden" name="token" value="">
        <button class="btn btn-primary btn-block" type="submit">
            Reset Password
        </button>
    </div>
```
Same goes for Firefox.

I'm presuming the rendering of the template is done by PHP so nginx vs Apache vs whatever shouldn't matter.

**Comment by claviska** [comment]
It matters a lot, actually. The `@request.get` variable that's referenced in `login.reset.hbs` originates from the query string, so it's likely that your nginx config isn't passing it along in the rewrite.

See [this answer](http://serverfault.com/a/362924) for a possible solution.

**Comment by jclacherty** [comment]
I'll investigate further and let you know what I find.

**Comment by jclacherty** [comment]
That's done it! I'll update the nginx config I posted in https://github.com/Postleaf/postleaf/issues/11 to reflect the changes.

**Comment by claviska** [comment]
Great! I think @calmdev's example uses `$args` instead of `$query_string`, but they do pretty much the same thing.
