### ISSUE TITLE
Administrator Login redirect

### ISSUE THREAD

**Issue by cosmospham** [Postleaf/postleaf#44]
### Issue Summary

Not redirect to admin control panel after login. It redirects to the login form. Reloading the page will show the admin CP.

### Steps to Reproduce

I create an admin role account and try login. You can see the demo at http://postleaf.buu.vn/admin/
Username: `demo`
Password: `5*LS+4Tpe(Fv3%](`

### Additional info

- Postleaf version: Latest commit
- PHP version: `PHP 5.6.24-1~dotdeb+7.1 (cli) (built: Jul 22 2016 00:07:27)`
- Affected browsers: `Chrome Version 52.0.2743.116 (64-bit)`
- Operating system: `Debian 8.5`

**Comment by claviska** [comment]
Works for me. Try clearing the authToken cookie and make sure you have cookies enabled.

**Comment by cosmospham** [comment]
I used incognito window. However I've just tried FireFox - NO private tab, **the same problem occurs**.

The second time login it does not occur.

**Comment by claviska** [comment]
Is there a token in the `authToken` after it fails?

**Comment by harikt** [comment]
I can confirm the demo login works for me.

**Comment by claviska** [comment]
Any update on this? Does it create an auth token cookie when you hit _Login_? What's the response of the XHR request to login?

**Comment by claviska** [comment]
If this is still an issue, comment on it with more details. It would also help to know what web server you're running (Apache, Nginx, etc.). Closing because I haven't heard anything in four days and I'm not getting any other reports like this, so it's likely some kind of config issue on your end.
