### ISSUE TITLE
Caddy Support

### ISSUE THREAD

**Issue by calmdev** [Postleaf/postleaf#45]
Thanks for using Postleaf! 💙💚

This issue tracker is ONLY for bug reports. If you need help with something or would like to request a feature, please ask on https://community.postleaf.org/ instead.

---

### Issue Summary

Support for Caddy was requested here https://github.com/Postleaf/postleaf/issues/11#issuecomment-237972816

### Steps to Reproduce

Tell us how to replicate the problem.

1. Try to run Postleaf using [Caddy](https://caddyserver.com/).

### Additional info

- Postleaf version: *
- PHP version: *
- Affected browsers: *
- Operating system: *

This is what appears to be working for me:

```
postleaf.dev:7755 {
  root ./app
  gzip
  tls off
  fastcgi / 127.0.0.1:9000 php
  rewrite {
    regexp ^/backups
    status 403
  }
  rewrite {
    to {path} {path}/ /index.php?{query}
  }
}
```

It would be good if someone else could verify it works for them too. Caddy isn't a web server I'm very familiar with, but maybe this will serve as a starting point. ~~I think the last rewrite rule can be improved on. Without it, tar file for backup downloads served by the API wouldn't work for me.~~ - fixed based on feedback from this issue and information found here mholt/caddy/issues/289

@doughnet

**Comment by harikt** [comment]
To the rewrite I have the query string also as `to {path} {path} /index.php?{query}` . Also not sure from where the app comes.

This is my `Caddyfile`, but it don't have something for the `backups` and it also fails for installation. (iirc) .

```
postleaf.localhost
gzip
tls off
root /var/www/projects/github.com/harikt/postleaf/postleaf-1.0.0-beta6
fastcgi / /var/run/php/php7.0-fpm.sock php
rewrite {
    to {path} {path} /index.php?{query}
}
```

**Comment by calmdev** [comment]
`{uri}` from my example also includes the query string:

https://caddyserver.com/docs/placeholders
> {uri} - The request URI (includes path, query string, and fragment)

I'm running postleaf directly from a github git clone of the repository. If you're downloading it as a zip file from the postleaf.org website I suppose the paths would need to be adjusted, because as you pointed out the `/app` directory otherwise doesn't exist.

When I configured the Caddyfile to test, it was against an already installed and running copy of postleaf. I tried again from scratch and see what you mean about the installer. Caddy can't seem to resolve the relative paths to assets that are used on the installer. However, when the paths are manually adjusted to be root relative, ie `/source/assets/...` instead of `../assets` they load fine.

If you fill out the form, the installer will actually still "work", though. Then everything from that point on seems normal for me. Once logged in pages are rendered using handlebars templates and a URL helper for generating the asset URLs. I'm not sure if same can be done for installer, or if the asset paths can be adjusted on the installer to not be relative, but if possible it'd prob solve the issue we're seeing with the installer @claviska

**Comment by claviska** [comment]
I'd be interested to know why relative URLs aren't working.

It's definitely possible to make them root relative (albeit a bit more challenging when Postleaf is installed in a subfolder), but I think the proper solution is to make relative paths work properly as they do with other servers.

Happy to look into this next week. I'm taking a break this weekend after a busy launch week 😓

**Comment by harikt** [comment]
@calmdev Thank you for sharing the information. New to Caddy also :) .

**Comment by calmdev** [comment]
FWIW, the installer loads correctly when a trailing slash is added to the URL. The issue with the second rewrite rule on the original example I posted is that it's trying to rewrite based on file extension instead of trying to resolve the request path to a file/directory that exists on the file system before applying the rewrite rule.

Basically what I think it needs is the apache equivalent of:

```shell
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
```

However, I'm not sure what that is. Anyways, hope it helps to find a solution.

**Comment by doughnet** [comment]
Thank you all for your help on this.  I greatly appreciate it.  With @harikt configuration code I was able to modify mine a bit and get it working.  This means the front end works, back end admin works & the backup generates plus allows me to download the file.  Below is what I used.

`caddy1.localhost.com {
tls email@temp.com
root /var/caddywww
gzip
log /var/log/caddy/access.log
errors /var/log/caddy/error.log
fastcgi / /var/run/php5-fpm.sock php


#POSTLEAF
rewrite {
    to {path} {path} /postleaf/index.php?{query}
}
}`
I was just amazed at how simple and quick it was to setup caddy and wanted to see how awesome it would be running with postleaf as well.  Just an FYI for all, I am using a 3rd party installer script for caddy which is amazing at how simple it is to use (even easier than caddy initially).  If interested this is the git: [https://github.com/sayem314/Caddy-Web-Server-Installer](https://github.com/sayem314/Caddy-Web-Server-Installer)

**Comment by harikt** [comment]
@doughnet Good to know it was helpful. 

Not sure what is the benefit of installer, for caddy itself is a simple executable.

**Comment by claviska** [comment]
Closing this since Postleaf will run just fine on Caddy, there's just not much we can do to configure it through the installer.

Tutorial here: https://www.postleaf.org/running-postleaf-on-caddy

**Comment by mholt** [comment]
Hi! This is cool. Just a couple thoughts.

I strongly recommend removing the line that says `tls off`. :wink: (Especially if you want to run on the standard ports; and note that specifying port 80 as in the blog post is redundant with `tls off`.)

Also note that, due to a [bug](https://github.com/mholt/caddy/issues/1012), status rewriting using `rewrite` will be disabled in the future and likely replaced with a new `status` directive exclusively for status rewriting.

**Comment by claviska** [comment]
I've updated the blog post accordingly.

Thanks for the heads up, @mholt, and excellent work on Caddy!

**Comment by claviska** [comment]
The assets issue @calmdev noticed has been fixed with [this commit](https://github.com/Postleaf/postleaf/commit/a100b26fee8f7c5a6ff77417422f304c7d34c6cf). (The installer redirect was just missing a slash.)
