### ISSUE TITLE
Editing Posts Not Working

### ISSUE THREAD

**Issue by crunchprank** [Postleaf/postleaf#46]
### Issue Summary

After initially creating a post, everything works as intended. However if you go back to edit that post and select to save, the post does not save.

### Steps to Reproduce

1. Create and publish a post.
2. Go back and try to edit that post.
3. Click Save

### Additional info

- Postleaf version: 1.0.0-beta6
- PHP version: 5.5.38
- MySQL: 5.5.31
- Operating system: CentOS 6 / Apache

### Steps taken to fix

- Temporarily set all permissions to 777

### Apache logs

Access Logs (PUT 404):
```
127.0.0.1 - - [06/Aug/2016:18:56:59 -0400] "PUT /blog/api/posts/postasdf HTTP/1.1" 404 556 "http://domain.com/blog/admin/posts/postasdf"
```

Error Logs
```
[Sat Aug 06 18:56:59.589097 2016] [access_compat:error] [pid 18461] [client 127.0.0.1:50498] AH01797: client denied by server configuration: /home/user/public_html/blog/api
```

**Comment by calmdev** [comment]
To me, it looks like your web server is not configured to allow `PUT` requests.

**Comment by crunchprank** [comment]
It's my understanding that Apache doesn't take into consideration what the method is and simply passes the request to the appropriate handler. It is dependent upon the script to handle the method that it is passed.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

Is this incorrect?

**Comment by claviska** [comment]
Sounds like server config. Have a look here: https://wiki.apache.org/httpd/ClientDeniedByServerConfiguration

If you identify what directive is causing this, please post back so we can make a note.

**Comment by crunchprank** [comment]
@claviska Thanks for the input. There must be some server configuration because when I explicitly state to allow PUT in an .htaccess file, it seems to work without issues.

That's very odd though because at no time did I configure this server to DENY or REQUIRE. Just for verification, I checked for any other .htaccess files higher up in the hierarchy that may have been affecting the directory that this blog was in recursively, but there's absolutely nothing there. There's also no oddities in the main HTTP config file that would be causing this. I'm at a complete loss. But! All that is my problem to sort out anyway.

Short of it is, it's working again and there must be something on my server that reject PUT requests. Thanks again for the help, guys.

**Comment by claviska** [comment]
Glad to hear it's working! 😄
