### ISSUE TITLE
Handlebars.js can't apply css/image/js in site?

### ISSUE THREAD

**Issue by vanloc0301** [Postleaf/postleaf#49]
### Issue Summary

I build a single page site; I only need information like name post, content, and image of this post.

In document of `HandleBar.js`:

> Handlebars templates look like regular HTML, with embedded handlebars expressions.

So, I think it will understand and render statics code in `*.html` file.

I was using `handlebars.js` into easy manipulate.

I also have the template of a website is HTML file.

I tried to add all code from `*.html` file to `*.hbs` file.

You can see like:

```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
    <title>Custom</title>

	<!-- Bootstrap CSS -->
	<link href="css/bootstrap.min.css" rel="stylesheet">
     <!-- CSS Custom -->
    <link rel="stylesheet" type="text/css" href="css/style.css">
<body>


<header class="navbar-fixed-top">
	<div class="container">
		<div class="col-md-2">
    		<div class="logo_img">
				<a href="#"><img src="images/logo.png" alt="logoimage"></a>
			</div>
		</div>

		<div class="col-md-10">
			<div class="menu_bar">
				<nav role="navigation" class="navbar navbar-default">
					<div class="collapse navbar-collapse" id="navbar">
						<ul class="nav navbar-nav">
						  <li><a href="#home" class="js-target-scroll">Home</a></li>
						  <li><a href="#services" class="js-target-scroll">About</a></li>
						</ul>
              		</div>
				</nav>
			</div>
        </div>
	</div>
</header>
</body>
</html>
```

In this code, will show like:

[![][1]][1]

It only shows only HTML code, seem CSS/JS/(link to an image) not working.

  [1]: http://i.stack.imgur.com/6oHJd.png

### Additional info

- Postleaf version: latest.

**Comment by claviska** [comment]
I'm not sure exactly what you're asking, but a couple things that might help:

1. Postleaf will only look at `.hbs` files in the theme directory. It will not look at .`.html` files.

2. References to scripts and stylesheets should look like this:
  ```html
  <link href="{{theme_url 'css/bootstrap.min.css'}}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{{theme_url 'css/style.css'}}">
  <img src="{{theme_url 'images/logo.png'}}" alt="logoimage">
  ```
  This will ensure that the stylesheet will always be linked properly, even if Postleaf is running from a subdirectory.

**Comment by claviska** [comment]
I hope my answer above helped. If not, please ask your question with more detail [on the forum](https://community.postleaf.org) so we can better help. I don't believe this is a problem with the software and I'm trying to reserve GitHub issues for bugs. 🙂 🐞

**Comment by vanloc0301** [comment]
Thank you very much @claviska
