### ISSUE TITLE
Ability to create tags while writing/editing posts

### ISSUE THREAD

**Issue by lukewatts** [Postleaf/postleaf#49]
Currently the only way to create new tags is to go to the tags section and create them there.

It would be a big time saver to simply be able to type them into the tags section of the Settings > Metadata panel when writing or editing a post and have them saved that way. Similar to as WordPress...but better...because it's not WordPress :)

**Comment by claviska** [comment]
See https://github.com/Postleaf/postleaf/issues/40#issuecomment-298473436

**Comment by lukewatts** [comment]
Ok. Well if it's a case where they need extra config why not have an "Add Tag" button on the Metadata panel which opens a modal where the user can properly configure the new Tag.

Or remove the ability to type at all from the metadata tags section and replace it with a select box and some more info about what tags are in Postleaf.

At the moment it's misleading being able to type only to realize they don't save after you save the post.

**Comment by claviska** [comment]
I have a feeling this will come up more often than I expected. I've reopened #40 for voting, so let's continue the discussion there.
