### ISSUE TITLE
Tags aren't sorted properly

### ISSUE THREAD

**Issue by juan-manuel-alberro** [Postleaf/postleaf#50]
### Summary

If you add a Tag in lower case the order doesn't work as expected

![](https://d2ppvlu71ri8gs.cloudfront.net/items/411Z2a3739172f3W0S02/Image%202017-05-09%20at%2022.09.44.png?v=64bffe9a)

### Steps to Reproduce

1. Go to Tags
2. Add new tag in lower case
3. Check the sorting

### Additional info

- Postleaf version: latest from master
- Node version: 7.8.0
- Affected browsers: all
- Operating system: all

---

Note: This issue tracker is ONLY for bug reports and feature requests. If this is a personal support issue, please ask on the forum instead: community.postleaf.org

**Comment by claviska** [comment]
This actually affected a lot more than just tags. Fixed in 8cd0555f6fb8ade354602d1c6d4fe33a4fb0c1a9.

Thanks for reporting this!
