### ISSUE TITLE
http/https urls

### ISSUE THREAD

**Issue by karsasmus** [Postleaf/postleaf#57]
Thanks for using Postleaf! 💙💚

This issue tracker is ONLY for bug reports. If you need help with something or would like to request a feature, please ask on https://community.postleaf.org/ instead.

---

### Issue Summary

Hello,
I'm using Cloud9 for developing.
Cloud9 serves the projects via https. It seems that Postleafs url helper function doesn't recognize the https and generates a http link for the theme files. Consequently Chrome doesn't load the theme files.

[Screenshot with Console](http://imgur.com/a/pIzeU)

### Steps to Reproduce

Tell us how to replicate the problem.

1. Serve postleaf over https

### Additional info

- Postleaf version: master branch
- PHP version: 5.5.9-1ubuntu4.17 
- Affected browsers: Chrome 52
- Operating system: ChromeOS

Provide any additional information that may be relevant to the bug here.

**Comment by karsasmus** [comment]
It seems, that this is perhaps Cloud9 related.
HTTPS in line 427 of Postleaf\Postleaf is empty although the site is served via https.

**Comment by micalm** [comment]
Cloud9 in fact doesn't fill in `$_SERVER['HTTPS']` properly, but it does return `$_SERVER['REQUEST_SCHEME']` with the value `https`. 
A quick check of my development server reveals that nginx 1.11.3 + php-fpm 7.0.10-1~dotdeb+8.1 returns both keys properly filled when requesting via https.

This is undocumented, but may be a (temporary) solution for some environments.

**Comment by karsasmus** [comment]
Thanks @micalm 
I added $_SERVER['REQUEST_SCHEME'] and now postleaf gets served via apache on cloud9.

**Comment by claviska** [comment]
There's a similar issued [mentioned here](https://github.com/Elgg/Elgg/issues/6190) that might be worth considering. Their solution was to generate a schema-relative URL:

```
//example.com/path/to/file.ext
```

I think this is worth considering, but we'd have to really look at how the URL methods are being used (since they all use `Postleaf::url()`) to make sure this won't cause any problems.

Reopening so we can consider this since SSL flags aren't always reliable.

**Comment by claviska** [comment]
I tried removing the protocol from the [URL method](https://github.com/Postleaf/postleaf/blob/master/app/source/classes/Postleaf.php#L453) and everything seems to work fine.

[Browser support](http://stackoverflow.com/a/4832046/567486) seems to be good. The only caveat is that IE7/8 will [download stylesheets twice](http://www.stevesouders.com/blog/2010/02/10/5a-missing-schema-double-download/) when referenced with schemalass URLs. I personally don't care about those browsers, and it probably won't be that noticeable for the handful of users who may be affected.

[This person](http://stackoverflow.com/questions/4831741/can-i-change-all-my-http-links-to-just#comment20380726_4832046) raises a good point about schemaless URLs in context, but I think it's safe to assume Postleaf will always be running either HTTP or HTTPS.

**Comment by claviska** [comment]
@karsasmus when you get a chance, can you verify that this also solves the issue with Cloud9?

**Comment by karsasmus** [comment]
@claviska I've tested it on Cloud9. It works fine. Thanks for your solution.

I've another question:
Should we also import external files like bootstrap, Lato and jQuery schemaless?

**Comment by claviska** [comment]
I don't know of any CDNs that don't support SSL, so you're better off using the `https://` prefix to ensure those are always served securely.
