### ISSUE TITLE
Template File Post.hbs is missing

### ISSUE THREAD

**Issue by Naoray** [Postleaf/postleaf#58]
### Issue Summary

The pre existing posts do not show up and I can't create new posts. -> pic
*post.hbs* template is missing
![image](https://cloud.githubusercontent.com/assets/10154100/17885759/e348993e-691e-11e6-86a8-37b351921e40.png)

### Steps to Reproduce

Tell us how to replicate the problem.

1. install postleaf as opposed
2. click on one existing post

### Additional info

- Postleaf version: master branch
- PHP version: 7.0.8 (cli)
- Affected browsers: Chrome Version 52.0.2743.116 m
- Operating system: Windows 10

**Comment by Naoray** [comment]
Ok sorry, it is #24 related!

Solved it!!!

**Comment by claviska** [comment]
Please see the installation notes. During the beta, if you're building yourself, you need to install the default range theme :)

Available at https://github.com/Postleaf/range

**Comment by claviska** [comment]
You got it. Replied from email before I saw this come in.
