### ISSUE TITLE
oEmbed support for embedding content

### ISSUE THREAD

**Issue by claviska** [Postleaf/postleaf#6]
Ability to paste in embed code or a URL. If a URL is pasted in, we should grab the appropriate embed code from the appropriate site and inject that instead.

Spec: http://oembed.com/

**Comment by Ema4rl** [comment]
I second this.
I suggest that postleaf should use [mpratt/Embera](https://github.com/mpratt/Embera) internally with the embed:// prefix enabled. An excerpt from Embera's docs:

    $config = array(
        'use_embed_prefix' => true
    );

    $text = 'embed://dailymotion.com/video/xp30q9_bmw-serie3-2012-en-mexico_auto
             http://youtube.com/watch?v=J---aiyznGQ';

    $embera = new \Embera\Embera($config);

    echo $embera->autoEmbed($text);
    // Only the dailymotion link will be autoconverted

I'll definitely send a pull request when I have spare time to roll-up postleaf.

Thumbs up!

**Comment by claviska** [comment]
Looks like a good fit. My thoughts were to parse the contents of the embed textarea. If a URL is found, try to get the embed code using the appropriate oEmbed tool. If not, insert the embed code as usual. I'll play around with it this week.

**Comment by UaMV** [comment]
[This](http://s9etextformatter.readthedocs.io/Plugins/MediaEmbed/Sites/) by @s9e could be a good alternative for embeds. It is currently in use as an extension for the [Flarum project](https://discuss.flarum.org/d/647-s9e-mediaembed-embed-videos-and-third-party-content).

**Comment by claviska** [comment]
Big thanks to @Ema4rl for the Embera suggestion. Awesome little library. 👍

**Comment by claviska** [comment]
This was added and will make it into 1.0.0-beta5 in the next day or two. You can now enter a URL into the Embed tool and, if an oEmbed provider is found, the resulting code will be embedded.

I also made it so URLs pasted directly into the editor will be converted to the appropriate embed code if an oEmbed provider is found. See e5d399d.
