### ISSUE TITLE
admin-theme does not work

### ISSUE THREAD

**Issue by d1rk** [Postleaf/postleaf#61]
### Summary

After installing according to readme, admin-theme does not work, since it can't load the `assets/css/lib.css` because, it is referenced without the port (3000).

generated markup from `http://localhost:3000/admin/posts`

```
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="/assets/images/favicon.png">
  <link rel="apple-touch-icon" href="/assets/images/app_icon.png">
  <link rel="stylesheet" href="http://localhost/assets/css/lib.css">
```

i exactly followed the readme:

```
git clone https://github.com/Postleaf/postleaf.git && cd postleaf
git clone https://github.com/Postleaf/empower-theme.git themes/empower-theme
cp .env.example .env
vim .env
npm install
sudo npm install -g gulp-cli
gulp build
node app.js
```

I just updated the upper part of .env to:

```
# App
NODE_ENV=production
APP_URL=http://localhost/
APP_PORT=3000

[...]
```

opened browser, to http://localhost:3000/

It guided me through creating the user (already unstyled). Frontend works fine.

### Additional info

- Postleaf version: latest master (876c2646f3326820a63aeffc9b29bc94e88622ac)
- Node version: v6.10.1
- Affected browsers: Safari
- Operating system: macOS Sierra 10.12.5 (not really relevant)

Thank you for your help and good work.

**Comment by claviska** [comment]
Your APP_URL needs to include the port for dev since there's no proxy:

http://local host:3000/

**Comment by d1rk** [comment]
Thanks for the clarification.
