### ISSUE TITLE
Embed alignment

### ISSUE THREAD

**Issue by karsasmus** [Postleaf/postleaf#61]
Thanks for using Postleaf! 💙💚

This issue tracker is ONLY for bug reports. If you need help with something or would like to request a feature, please ask on https://community.postleaf.org/ instead.

---

### Issue Summary

Alignment issues with embeds.

center: Text is marked, you can't add a new line nor delete the mark
![align center](https://cloud.githubusercontent.com/assets/6382544/17918787/47fdb9c8-69c8-11e6-8349-9e6d40348b17.png)

right:
![align right](https://cloud.githubusercontent.com/assets/6382544/17918845/b8c66e84-69c8-11e6-9f27-3fcb2017696c.png)

left:
![left align](https://cloud.githubusercontent.com/assets/6382544/17918851/d8c72d4a-69c8-11e6-9208-d205ad90e03b.png)

### Steps to Reproduce

Tell us how to replicate the problem.

1. Embed a simple link `<a href="something.html">
  Something
</a>`
2. choose alignment center
3. copy this embed
4. choose the copy's alignment right/left

### Additional info

- Postleaf version: master branch
- PHP version: 5.5.9
- Affected browsers: Chrome 52
- Operating system: Ubuntu/ChromeOS

**Comment by claviska** [comment]
You have to move the cursor left/right (to get it off the embed block) before hitting enter.

This is sort of an edge case as it's only really noticeable when you have _just_ an embed on the page. When you have content above/below you probably won't run into it very much.

Either way, this one is out of Postleaf's control. `contentEditable="false"` handling is completely up to TinyMCE, so improvements to this behavior should be submitted to [their project](https://github.com/tinymce/tinymce) :)
