### ISSUE TITLE
Backend caching

### ISSUE THREAD

**Issue by karsasmus** [Postleaf/postleaf#62]
Thanks for using Postleaf! 💙💚

This issue tracker is ONLY for bug reports. If you need help with something or would like to request a feature, please ask on https://community.postleaf.org/ instead.

---

### Issue Summary

Perhaps not a real issue, but i thought it's no problem to write this down.

I changed the setting "posts per page" from 10 to 3. The setting was properly saved - the frontend shows only 3 posts - but as I refreshed the settings page, the setting "posts per page" was 10. 
After the refresh, the cached site was loaded.

### Steps to Reproduce

Tell us how to replicate the problem.

1. Change setting "posts per page"
2. Reload/Refresh the site
3. Setting "posts per page" has the old value

### Additional info

- Postleaf version: master branch
- PHP version: 5.5.9
- Affected browsers: Chrome 52
- Operating system: Ubuntu/ChromeOS

Provide any additional information that may be relevant to the bug here.

**Comment by claviska** [comment]
I can't replicate this. Can you confirm the value of `settings.posts_per_page` in the database after saving? Are there any PHP/MySQL errors after saving? What about your JS console?

**Comment by karsasmus** [comment]
Hmm... I checked it twice and I couldn't reproduce the issue, too. Everytime the database and the frontend are updated properly, no caching issue.

**Comment by karsasmus** [comment]
I'll close this issue.
After more tests, no caching issue.
