### ISSUE TITLE
Adding a left-aligned image makes the editor unusable

### ISSUE THREAD

**Issue by kshep92** [Postleaf/postleaf#63]
After inserting an image and setting it to be left-aligned, the footer "collapses" in on the editor and makes further authoring impossible. See screenshot:

![ghost-float](https://user-images.githubusercontent.com/3780572/27584344-a1f06fbe-5b05-11e7-99aa-bdfb18960aba.png)

This can be corrected by setting the alignment to center or none, but even after that it becomes impossible to add a paragraph below the picture and continue writing the post.

### Steps to recreate

- Create a new post
- Insert an image
- Choose left alignment in the options panel

**Comment by claviska** [comment]
Are you using a custom theme or one of the ones in the repo? Seems like a CSS issue.

**Comment by kshep92** [comment]
I've only used the built-in themes thus far. It happens on Empower and Lanyon. Casper works but Roon only displays full-width images.

**Comment by claviska** [comment]
This is a style issue in the respective themes. Fixed in https://github.com/Postleaf/roon-theme/commit/085571bc1091839d9e1c2b10f809cad3c8c95f97 and https://github.com/Postleaf/lanyon-theme/commit/4f552f9ac8cdb37c45c30e34d65b65ef0f3a6884.
