### ISSUE TITLE
Determine a more appropriate name for the "Cancel" link in the editor

### ISSUE THREAD

**Issue by kshep92** [Postleaf/postleaf#64]
Suggestion: Instead of "Cancel" to go back to the list of posts, how about a dedicated "Back to dashboard" link? I found there to be too much uncertainty when clicking a "Cancel" button after writing a nice, long post.

**Comment by claviska** [comment]
How about "Exit"?

**Comment by kshep92** [comment]
Dashboard?

**Comment by claviska** [comment]
It doesn't go to the dashboard. It goes to the posts page. 🤷🏻‍♂️

**Comment by kshep92** [comment]
Well, how about <= Back to posts or Done

**Comment by claviska** [comment]
"Back to posts" is too long, especially when translated. Done might work. Thoughts on "close"?

**Comment by kshep92** [comment]
Done has more of a finality to it, and seems to make more sense semantically given the context: "I'm done writing my post." Close sounds more like a generic application function "Close this window." I'd go with Done.

**Comment by claviska** [comment]
I'm torn between "Done" and "Back." For consistency, it should also be applied to Edit Tag and Edit User.

**Comment by kshep92** [comment]
Back is good, I can live with that.

**Comment by claviska** [comment]
I went with "Done." Definitely feels better now. Fixed in 473796611557d4f59fe5c62f6332f45ed6c65327
