### ISSUE TITLE
Language Pack Case Sensitivity

### ISSUE THREAD

**Issue by icaromh** [Postleaf/postleaf#65]
### Issue Summary

So have some issues with camelcase files in **languages directory** 

### Steps to Reproduce

![captura de tela_2016-08-24_16-32-37](https://cloud.githubusercontent.com/assets/3057676/17945049/88b69a0c-6a18-11e6-9a37-79a44c3410ed.png)

1. Change your language to pt-PT
2. Refresh the page

### Additional info

- Postleaf version: lastest
- PHP version: 7
- Affected browsers: tested on Firefox and Chrome
- Operating system: Xubuntu 16.04

I'hve fixed renaming the file:

`app/source/languages/pt-pt.php -> app/source/languages/pt-PT.php`

I think that doesn't need an pull request, but I can do it if you like :smile:

**Comment by icaromh** [comment]
Well, I've created an pull request to fix that and add PT-BR translation :dancer: 
#69

**Comment by claviska** [comment]
As mentioned in #69, this needs to be addressed in `Language.php` so we can obtain the filename/path independent of the language code.

Thanks for reporting this!

**Comment by icaromh** [comment]
Oh, sure! :dancer: 

Should I make new pull request to add pt-BR translation or aren't need?

**Comment by claviska** [comment]
Nah, the file will stay the same. Just need to change how it's referenced (currently using the language code, but it will change to use the actual pathname).

**Comment by icaromh** [comment]
Sorry, I mean add translantion to Brazilian Portuguese(pt-br), rigth now just have Portuguese(pt) translation.

**Comment by claviska** [comment]
Whoops, sorry! Didn't notice that the PR was for pt-br! I'll accept now and adjust for consistency.

**Comment by icaromh** [comment]
@claviska Could you do the same in pt-br? 

because: 
```
Language pack not found: pt-BR.php
```

**Comment by claviska** [comment]
Missed that one. Done.
