### ISSUE TITLE
Image upload fails

### ISSUE THREAD

**Issue by himalikiran** [Postleaf/postleaf#68]
any image upload fails. Any solution?

error log:
2016/08/24 16:24:45 [error] 1531#1531: *14 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 116.66.198.52, server: himalikiran.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "himalikiran.com"

**Comment by claviska** [comment]
Might be relevant: http://serverfault.com/questions/517190/nginx-1-fastcgi-sent-in-stderr-primary-script-unknown

Seems like a config issue, not a Postleaf issue.

**Comment by himalikiran** [comment]
Thank you @claviska I figured out that the problem is about open_basedir configuration in my php.ini file.
now it is working perfectly. 
By the way does postleaf supports Ghost themes?

**Comment by claviska** [comment]
Glad it's working 👍

While Postleaf does use handlebar templates, it doesn't support Ghost themes without certain modifications.

While Ghost is awesome in its own way, there are fundamental differences in certain aspects of each system and I didn't want to have to keep up with their API while managing our own.

One user wrote up a very through post about converting his Ghost theme to Postleaf:

https://www.0x0049.me/switching-from-ghost-to-postleaf

In fact, this is something I should probably throw up on the site as a tutorial.
