### ISSUE TITLE
Filter out data-mce-* attributes from copy/pasted embed blocks

### ISSUE THREAD

**Issue by claviska** [Postleaf/postleaf#7]
To replicate:

1. Insert an embed block with this HTML:

  ```html
  <a href="something.html">
    Something
  </a>
  ```

2. Copy the embed block and paste it elsewhere in the document.

3. The new embed block will have this HTML:

  ```html
  <a href="http://dev.postleaf.dev/something.html" data-mce-href="something.html">
    Something
  </a>
  ```

The `<div>` container will also have a lot of inline styles, but that's a TinyMCE paste issue.

**Comment by karsasmus** [comment]
I've worked today on this issue.
I wrote code to strip the data-mce-*-tags, logging on console was pretty (without the tags), but in the editor there were this tags.

After 2 or 3 hours of testing and coding, i found this:
http://archive.tinymce.com/forum/viewtopic.php?id=35717

The editor strips out the data-mce-* tags if you call editor.getContent().

**Comment by claviska** [comment]
The embed code is getting pulled from the [`data-embed` attribute](https://github.com/Postleaf/postleaf/blob/master/app/source/scripts/posts.edit.js#L1115). This is supposed to be an unmodified version of the embed code.

What happens is, when you copy/paste an existing embed block into the editor, TinyMCE adds `data-mce-href` attributes to normalize browser behavior before Postleaf can process them as embeds. As a result, `data-mce-href` erroneously ends up inside `data-embed` attribute.

Calling `getContent()` _will_ remove them from the embed itself, but not from the escaped code in the `data-embed` attribute.

Without an HTML parser at our disposal, there are a few options:

1. Use a regex to remove the unwanted attributes (dirty)
2. Utilize some TinyMCE magic to clean them up the embed code (difficult because TinyMCE is abstracted through `editor.js` and the embed code is fetched directly in `posts.edit.js`; might be possible to add a cleanup method to `editor.js` to filter the code through)
3. Try to remove the attributes with JavaScript after the paste (probably the best option)

I'm open to other ideas as well, but I'd prefer not to add an HTML parser dependency for such a small issue.

**Comment by claviska** [comment]
Totally spaced out and forgot that we _do_ have an HTML parser at our disposal, at least in JavaScript.

The fix was to run the innerHTML through a function that strips out `data-mce-*` attributes before storing the content in `data-embed`. See 8bdcbf0 for details.
