### ISSUE TITLE
Centered images are right-aligned instead

### ISSUE THREAD

**Issue by meulie** [Postleaf/postleaf#76]
On beta7 I noticed that when I specify an image should be centred, it is in fact aligned right.
Here's an example: First image is aligned left, 2nd image is aligned centre, 3rd image is aligned right:

https://blaadje.meulie.net/image-test

As you can see the centred & right-aligned image both show right-aligned.

(This is with theme Casper, in case that makes a difference)

**Comment by karsasmus** [comment]
It's a theme related issue :smile: 

Open assets/css/screen.css, go to line 2290 and comment out "left: 50%".
Your image should be centered now.

**Comment by claviska** [comment]
Correct. Checkout the section "Alignment Classes" on [this post](https://www.postleaf.org/designing-your-first-theme) to learn more about how Postleaf handles alignment.
