### ISSUE TITLE
False pub_date

### ISSUE THREAD

**Issue by karsasmus** [Postleaf/postleaf#83]
This issue tracker is ONLY for bug reports. If you need help with something or would like to request a feature, please ask on https://community.postleaf.org/ instead.

---

### Issue Summary

[Question in the forum.](https://community.postleaf.org/t/how-to-change-the-post-date/254)

### Steps to Reproduce

Tell us how to replicate the problem.

1. Open a post
2. Edit the pub date
3. Save

pub_date == actual date.

The date in the properties array has the format YYYY-MM-DD **@** HH:MM.
strtotime can't parse this format.

### Additional info

- Postleaf version:
- PHP version:
- Affected browsers: Chrome 52
- Operating system: Ubuntu / Win10

Provide any additional information that may be relevant to the bug here.

**Comment by karsasmus** [comment]
On Chrome 53 this issue doesn't exist.

**Comment by claviska** [comment]
From what I can tell, the user [is asking](https://community.postleaf.org/t/how-to-change-the-post-date/254) why the date is changing when he updates a post. This shouldn't be happening, I can't replicate his issue in my dev environment, and I'm not even sure what browser or Postleaf version he's using (I've asked in the forum).

I'm also not sure what #84 is trying to fix. Why are we parsing out at `@` symbol which was removed in 4a9c84fdfd660b0aad63ee3c2eb8368493441dad?

Is the user entering `@` out of habit? Need more info to properly assess.

**Comment by karsasmus** [comment]
On Chrome 52 and 53, the data in pub_date has this @ between date and time. 

![date](https://cloud.githubusercontent.com/assets/6382544/18394105/940488a4-76b8-11e6-8c05-8f3a73e3fdda.png)

In Post.php at line 837 var_dump($properties['pub_date'])

**Comment by claviska** [comment]
The post date is passed from the database to the controller to the view in `YYYY-MM-DD HH:MM:SS`. Chrome 53, Postleaf master.

The user said he's on 1.0.0-beta7 which isn't the latest. I suspect this might be part of the problem.

**Comment by karsasmus** [comment]
I did a var_dump after array_merge, same result.

**Comment by claviska** [comment]
I verified it at each step all the way to the view. Here's the raw dump from the view:

![screen shot 2016-09-09 at 12 21 38 pm](https://cloud.githubusercontent.com/assets/55639/18394436/fe2ba9aa-7687-11e6-9e70-8bc276d2e0bc.png)

Are you up to date with master?

**Comment by claviska** [comment]
If you are seeing an `@` on update then it might be coming from an old or even a cached script. [This line](https://github.com/Postleaf/postleaf/blob/master/app/source/scripts/posts.edit.js#L517) used to create it, but it doesn't anymore.

**Comment by karsasmus** [comment]
Hmm... I'm on master and I cloned today the master branch for the event pull request.

I've deleted the files in the assets folder, build all files with gulp and deleted the browser cache.
It seems that my issue is a caching issue. 
Sorry for that 😢

**Comment by claviska** [comment]
No worries, glad it's sorted. 😎
