### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by 1k2k** [Postleaf/postleaf#88]
### Summary

Please summarize your issue here.

### Steps to Reproduce

1. Step one
2. Step two
3. ...

### Additional info

- Postleaf version:
- Node version:
- Affected browsers:
- Operating system:

---

Note: This issue tracker is ONLY for bug reports and feature requests. If this is a personal support issue, please visit postleaf.org/support.

**Comment by claviska** [comment]
Currently, SQLite is the only officially supported database. However, it wouldn't be hard to add support for MySQL, MariaDB, MSSQL, and/or PostgreSQL since Sequelize already supports them. MongoDB is an [unlikely candidate](https://github.com/sequelize/sequelize/issues/1931), though.
