### ISSUE TITLE
React for the dashboard

### ISSUE THREAD

**Issue by 1k2k** [Postleaf/postleaf#89]
### Summary

Please summarize your issue here.

### Steps to Reproduce

1. Step one
2. Step two
3. ...

### Additional info

- Postleaf version:
- Node version:
- Affected browsers:
- Operating system:

---

Note: This issue tracker is ONLY for bug reports and feature requests. If this is a personal support issue, please visit postleaf.org/support.

**Comment by claviska** [comment]
I'm not interested in using React for Postleaf anytime soon.
